### ISSUE TITLE
Error generating pendulum data

### ISSUE THREAD

**Issue by PranavMahajan25** [orilinial/GOKU#1]
gym version 0.11.0
scikit-image version 0.16.2

Is this error due to scikit image/gym or an error in the preproc() function code? Any pointers towards solving this would help and/or sharing the pendulum data with a drive link would help too! Thanks.
```
python3 create_data.py --model pendulum
  0%|                                                                     | 0/500 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "create_data.py", line 130, in <module>
    make_dataset(args)
  File "create_data.py", line 49, in make_dataset
    raw_data, latent_data, params_data = args.create_raw_data(args)
  File "/home/pranav/GIT_repos/GOKU/utils/create_pendulum_data.py", line 78, in create_pendulum_data
    processed_frame = preproc(env.render('rgb_array'), side)
  File "/home/pranav/GIT_repos/GOKU/utils/create_pendulum_data.py", line 19, in preproc
    return skimage.transform.resize(X, [int(side), side]) / 255.
  File "/home/pranav/anaconda3/envs/my_lab/lib/python3.6/site-packages/skimage/transform/_warps.py", line 166, in resize
    preserve_range=preserve_range)
  File "/home/pranav/anaconda3/envs/my_lab/lib/python3.6/site-packages/skimage/transform/_warps.py", line 807, in warp
    raise ValueError("Cannot warp empty image with dimensions", image.shape)
ValueError: ('Cannot warp empty image with dimensions', (0, 0))
Exception ignored in: <bound method Viewer.__del__ of <gym.envs.classic_control.rendering.Viewer object at 0x7fcf3301eda0>>
Traceback (most recent call last):
  File "/home/pranav/anaconda3/envs/my_lab/lib/python3.6/site-packages/gym/envs/classic_control/rendering.py", line 143, in __del__
  File "/home/pranav/anaconda3/envs/my_lab/lib/python3.6/site-packages/gym/envs/classic_control/rendering.py", line 62, in close
  File "/home/pranav/anaconda3/envs/my_lab/lib/python3.6/site-packages/pyglet/window/xlib/__init__.py", line 480, in close
  File "/home/pranav/anaconda3/envs/my_lab/lib/python3.6/site-packages/pyglet/gl/xlib.py", line 345, in destroy
  File "/home/pranav/anaconda3/envs/my_lab/lib/python3.6/site-packages/pyglet/gl/base.py", line 334, in destroy
  File "/home/pranav/anaconda3/envs/my_lab/lib/python3.6/site-packages/pyglet/gl/xlib.py", line 335, in detach
  File "/home/pranav/anaconda3/envs/my_lab/lib/python3.6/site-packages/pyglet/gl/lib.py", line 97, in errcheck
ImportError: sys.meta_path is None, Python is likely shutting down

```

**Comment by orilinial** [comment]
Thanks for bringing this problem to my attention.
Apparently there was a small change in the images size in the pendulum's dataset. As stated in the paper, we followed exactly the data generation process as in the HNN paper, and for some reason the images size changed.
I updated the code and it should work now. If any other problems occur, please let me know.
